export enum DocumentPurposeEnum{

    DRIVER_VERIFICATION_DRIVING_LICENSE,
    DRIVER_VERIFICATION_ADHAAR_CARD,
    TAP_VERIFICATION_GST,
    TAP_VERIFICATION_AGREEMENT_COPY,
    CLIENT_VERIFICATION_AGREEMENT_COPY,
    CLIENT_VERIFICATION_GST,
    VEHICLE_VERIFICATION_REGISTRATION_CERTIFICATE,
    VEHICLE_VERIFICATION_POLLUTION_CERTIFICATE,
    VEHICLE_VERIFICATION_INSURANCE_CERTIFICATE,
    VEHICLE_VERIFICATION_PERMIT,
    TRUCKBUDDY_VERIFICATION_ADHAAR,
	TRUCKBUDDY_VERIFICATION_PAN,
}